export const MAX_LAYOUT_PERMITTED = 5;

export const AppLayoutDefault = [
  {
    label: 'Logo de la app',
    name: 'APP_LOGO',
    status: 'ACTIVE',
    type: 'IMAGE',
    value: null,
  },
  {
    label: 'Imagen de fondo',
    name: 'APP_BACKGROUND_IMAGE',
    status: 'ACTIVE',
    type: 'IMAGE',
    value: null,
  },
  {
    label: 'Tipo de fondo de la app',
    name: 'APP_BACKGROUND_TYPE',
    status: 'ACTIVE',
    type: 'SELECT',
    value: {
      options: [
        {
          label: 'Imagen',
          value: 'IMAGE',
        },
        {
          label: 'Color',
          value: 'COLOR',
        },
      ],
      selected: 'COLOR',
    },
  },
  {
    label: 'Color de fondo',
    name: 'APP_BACKGROUND_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#080e16c7',
  },
  {
    label: 'Color de la tarjeta inicial',
    name: 'APP_CARD_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#1d242e73',
  },
  {
    label: 'Borde de la tarjeta inicial',
    name: 'APP_CARD_RADIUS',
    status: 'ACTIVE',
    type: 'INTEGER',
    value: 20,
  },
  {
    label: 'Color de la tarjeta de estado',
    name: 'APP_CARD_STATUS_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#1d242e73',
  },
  {
    label: 'Borde de la tarjeta de estado',
    name: 'APP_CARD_STATUS_RADIUS',
    status: 'ACTIVE',
    type: 'INTEGER',
    value: 25,
  },
  {
    label: 'Color de la tarjeta de configuración',
    name: 'APP_CARD_CONFIG_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#080e16c7',
  },
  {
    label: 'Color de fondo de los diálogos',
    name: 'APP_DIALOG_BACKGROUND_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#080e16c7',
  },
  {
    label: 'Color de fondo del diálogo de registro',
    name: 'APP_DIALOG_LOGGER_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#080e16c7',
  },
  {
    label: 'Color de los bordes',
    name: 'APP_BORDER_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#1d242e73',
  },
  {
    label: 'Color de los inputs',
    name: 'APP_INPUT_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#1d242e73',
  },
  {
    label: 'Borde de los inputs',
    name: 'APP_INPUT_RADIUS',
    status: 'ACTIVE',
    type: 'INTEGER',
    value: 25,
  },
  {
    label: 'Color de los textos',
    name: 'APP_TEXT_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#FFFFFFFF',
  },
  {
    label: 'Color de los botones',
    name: 'APP_BUTTON_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#1d242e73',
  },
  {
    label: 'Borde de los botones',
    name: 'APP_BUTTON_RADIUS',
    status: 'ACTIVE',
    type: 'INTEGER',
    value: 25,
  },
  {
    label: 'Color de los iconos',
    name: 'APP_ICON_COLOR',
    status: 'ACTIVE',
    type: 'COLOR',
    value: '#FFFFFFFF',
  },
  {
    label: 'Mostrar modo de conexión',
    name: 'APP_SHOW_CONNECTION_MODE',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Actualización automática de configuraciones',
    name: 'APP_CONFIG_AUTO_UPDATE',
    status: 'ACTIVE',
    value: true,
    type: 'BOOLEAN',
  },
  {
    label: 'Usar limitador de conexión',
    name: 'APP_CONNECTION_LIMITER',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'Usar botón de actualizaciones',
    name: 'APP_BTN_UPDATE_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Usar botón de registros',
    name: 'APP_BTN_LOGGER_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Usar botón de página webview',
    name: 'APP_BTN_PAGE_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'Usar botón de menú',
    name: 'APP_BTN_MENU_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Usar actualización de visto por última vez',
    name: 'APP_UPDATE_LAST_SEEN_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'Pedir permiso de ubicación del usuario',
    name: 'APP_CONFIG_LOCATION_PERMISSION',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'Activar diálogo de errores',
    name: 'APP_DIALOG_ERROR_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Activar diálogo de checkuser',
    name: 'APP_CHECKUSER_DIALOG_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'Activar diálogo de notificaciones',
    name: 'APP_DIALOG_NOTIFICATION_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Activar notificaciones de éxito',
    name: 'APP_SUCCESS_TOAST_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Activar notificaciones de error',
    name: 'APP_ERROR_TOAST_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Activar IP local en el diseño nativo',
    name: 'APP_LOCAL_IP_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Filtrar configuraciones por nombre de red',
    name: 'APP_CONFIG_FILTER_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'Activar servicio de ping',
    name: 'APP_PING_SERVICE_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Activar verificación de conectividad',
    name: 'APP_CONNECTIVITY_CHECK_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Mostrar cantidad de CDNs',
    name: 'APP_CDN_COUNT_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Activar modo avión automático',
    name: 'APP_AIRPLANE_MODE',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'Tiempo de espera del modo avión automático (en segundos)',
    name: 'APP_AIRPLANE_MODE_TIMEOUT',
    status: 'ACTIVE',
    type: 'INTEGER',
    value: 1,
  },
  {
    label: 'Activar sonidos de alerta',
    name: 'APP_ALERT_SOUND_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: true,
  },
  {
    label: 'Versión de la aplicación',
    name: 'APP_CURRENT_VERSION',
    status: 'ACTIVE',
    type: 'STRING',
    value: '1.0.0',
  },
  {
    label: 'Link para descargar la aplicación',
    name: 'APP_DOWNLOAD_URL',
    status: 'ACTIVE',
    type: 'STRING',
    value: null,
  },
  {
    label: 'Usar diseño webview',
    name: 'APP_LAYOUT_WEBVIEW_ENABLED',
    status: 'ACTIVE',
    type: 'BOOLEAN',
    value: false,
  },
  {
    label: 'DISEÑO WEBVIEW (BAJO TU RESPONSABILIDAD)',
    name: 'APP_LAYOUT_WEBVIEW',
    status: 'ACTIVE',
    type: 'HTML',
    value: null,
  },
  {
    label: 'ANDROID WEBVIEW (BAJO TU RESPONSABILIDAD)',
    name: 'APP_SUPPORT_BUTTON',
    status: 'ACTIVE',
    type: 'HTML',
    value: null,
  },
  {
    label: 'PÁGINA WEBVIEW (BAJO TU RESPONSABILIDAD)',
    name: 'APP_WEB_VIEW',
    status: 'ACTIVE',
    type: 'HTML',
    value: null,
  },
];
