const AppTextDefault = [
  { label: 'LBL_BTN_START', text: 'INICIAR' },
  { label: 'LBL_BTN_STOPPING', text: 'DETENIENDO' },
  { label: 'LBL_BTN_STOP', text: 'DETENER' },
  { label: 'LBL_BTN_RECONNECT', text: 'RECONECTAR' },
  { label: 'LBL_DISCONNECTED', text: '<b>Desconectado</b>' },
  { label: 'LBL_RECORD', text: 'REGISTRO' },
  { label: 'LBL_CHOOSE_CONFIG', text: 'ELIGE UNA CONFIGURACIÓN' },
  { label: 'LBL_UUID', text: 'UUID V2Ray' },
  { label: 'LBL_USERNAME', text: 'Usuario' },
  { label: 'LBL_PASSWORD', text: 'Contraseña' },
  { label: 'LBL_UUID_INVALID', text: 'UUID inválido' },
  { label: 'LBL_USERNAME_INVALID', text: 'Usuario inválido' },
  { label: 'LBL_PASSWORD_INVALID', text: 'Contraseña inválida' },
  { label: 'LBL_USERNAME_PASSWORD_INVALID', text: 'Por favor, ingresa usuario y contraseña' },
  { label: 'LBL_CONFIG_TITLE', text: 'Configuración' },
  { label: 'LBL_INITIALIZING_APP', text: 'Iniciando aplicación' },
  { label: 'LBL_CONFIG_LOADED', text: 'Configuración cargada' },
  { label: 'LBL_SEARCHING_FOR_UPDATES', text: 'Buscando actualizaciones' },
  { label: 'LBL_CONFIG_UPDATED', text: 'Configuraciones actualizadas con éxito' },
  { label: 'LBL_APP_CONFIG_UPDATED', text: 'Configuraciones de la app actualizadas con éxito' },
  { label: 'LBL_APP_TEXT_UPDATED', text: 'Textos de la app actualizados con éxito' },
  { label: 'LBL_CONFIG_NOT_SUPPORTED', text: 'Parece que esta configuración no es compatible con esta aplicación' },
  { label: 'LBL_ERROR_ESTABLISHING_CONNECTION_SSH', text: '<b>Error al establecer conexión SSH</b>' },
  { label: 'LBL_RECONNECTION_PROCESS', text: 'Proceso de reconexión' },
  { label: 'LBL_RECONNECTING_IN', text: 'Reconectando en: %ss' },
  { label: 'LBL_RECONNECTING', text: 'Reconectando...' },
  { label: 'LBL_CONNECTING', text: 'Conectando...' },
  { label: 'LBL_STOPPING', text: 'Deteniendo...' },
  { label: 'LBL_LOCAL_NETWORK_IP', text: '{NETWORK}: {IP}' },
  { label: 'LBL_LOCAL_IP', text: 'IP Local: %s' },
  { label: 'LBL_LOCAL_IP_INFO', text: 'IPv4 Local: %1$s/%2$d MTU: %3$d' },
  { label: 'LBL_DNS_SERVER_INFO', text: 'Servidor DNS: %s' },
  { label: 'LBL_ROUTES_INFO_INCL', text: 'Rutas: %s' },
  { label: 'LBL_ROUTES_INFO_EXCL', text: 'Rutas excluidas: %s' },
  { label: 'LBL_INVALID_CONFIG_OVPN', text: 'Configuración OVPN inválida' },
  { label: 'LBL_ERROR', text: 'Error: %s' },
  { label: 'LBL_CONFIG_NOT_FOUND_TITLE', text: 'Configuración no encontrada' },
  { label: 'LBL_CONFIG_NOT_FOUND_TEXT', text: 'No se encontró ninguna configuración' },
  { label: 'LBL_STOP_APPLICATION', text: 'Para continuar, detén la aplicación' },
  { label: 'LBL_FINGERPRINT', text: '<b>Huella digital: %s</b>' },
  { label: 'LBL_AUTHENTICATING', text: 'Autenticando...' },
  { label: 'LBL_AUTHENTICATION_SUCCESS', text: '<b>Autenticación realizada con éxito</b>' },
  { label: 'LBL_AUTHENTICATION_FAILED', text: 'Fallo en la autenticación' },
  { label: 'LBL_AUTHENTICATION_FAILED_TEXT', text: 'No se pudo autenticar con el servidor. Por favor, verifica tu usuario y contraseña.' },
  { label: 'LBL_STATE_CONNECTED', text: 'Conectado' },
  { label: 'LBL_STATE_DISCONNECTED', text: 'Desconectado' },
  { label: 'LBL_STATE_CONNECTING', text: 'Conectando' },
  { label: 'LBL_STATE_STOPPING', text: 'Deteniendo' },
  { label: 'LBL_STATE_NO_NETWORK', text: 'Sin acceso a internet' },
  { label: 'LBL_STATE_AUTH', text: 'Autenticando' },
  { label: 'LBL_STATE_AUTH_FAILED', text: 'Fallo en la autenticación' },
  { label: 'LBL_STATE_UNKNOWN', text: 'Desconocido' },
  { label: 'LBL_STATE_ASSIGN_IP', text: 'Asignando IP' },
  { label: 'LBL_STATE_ADD_ROUTES', text: 'Agregando rutas' },
  { label: 'LBL_STATE_RECONNECTING', text: 'Reconectando' },
  { label: 'LBL_STATE_EXITING', text: 'Saliendo' },
  { label: 'LBL_STATE_RESOLVE', text: 'Resolviendo' },
  { label: 'LBL_STATE_TCP_CONNECT', text: 'Conectando (TCP)' },
  { label: 'LBL_STATE_VPN_GENERATE_CONFIG', text: 'Generando configuración' },
  { label: 'LBL_STATE_WAIT', text: 'Esperando' },
  { label: 'LBL_STATE_GET_CONFIG', text: 'Obteniendo configuración' },
  { label: 'LBL_VPN_ESTABLISHED', text: '<b>VPN establecida</b>' },
  { label: 'LBL_APP_VERSION', text: '<b>%s %s %s</b>' },
  { label: 'LBL_MOBILE_INFO', text: '<b>%s | %s | %s | %s</b>' },
  { label: 'LBL_ROUTE_REJECTED', text: 'Ruta rechazada:' },
  { label: 'LBL_COULD_NOT_ADD_DNS', text: 'No se pudo agregar DNS:' },
  { label: 'LBL_ERROR_INTERFACE_TUN', text: 'Error al crear interfaz tun' },
  { label: 'LBL_OPENING_INTERFACE_TUN', text: 'Abriendo interfaz tun' },
  { label: 'LBL_CHECKING_USER', text: 'Verificando usuario...' },
  { label: 'LBL_CHECKING_USER_FAILED', text: 'Fallo al verificar usuario' },
  { label: 'LBL_OVPN_STARTED', text: 'OpenVPN iniciado' },
  { label: 'LBL_TLS_VERSION', text: '<b>Versión TLS: %s</b>' },
  { label: 'LBL_TLS_ALGORITHM', text: '<b>Algoritmo TLS: %s</b>' },
  { label: 'LBL_INVALID_IP', text: 'IP inválida: %s' },
  { label: 'LBL_CHECK_USER_TITLE', text: 'INFO. DEL USUARIO' },
  { label: 'LBL_CHECK_USER_MESSAGE', text: '👤 Usuario: {username}<br>📆 Expira: {expiration_date}<br>📅 Días restantes: {expiration_days}<br>🚫 Conexiones: {count_connections}|{limit_connections}' },
  { label: 'LBL_NETWORK_STATUS', text: 'Estado de la red: %s' },
  { label: 'LBL_WELCOME', text: 'Bienvenido(a)' },
  { label: 'LBL_INFO', text: 'Aviso' },
  { label: 'LBL_ALERT', text: 'Alerta' },
  { label: 'LBL_SSH_LIB_NOT_FOUND', text: 'SSH no encontrado' },
  { label: 'LBL_V2RAY_NOT_FOUND', text: 'V2Ray no encontrado' },
  { label: 'LBL_OPENVPN_NOT_FOUND', text: 'OpenVPN no encontrado' },
  { label: 'LBL_APP_DEPRECATED_TITLE', text: 'Actualizar Aplicación' },
  { label: 'LBL_APP_DEPRECATED_MESSAGE', text: 'Descarga y actualiza a la nueva versión más reciente:' },
  { label: 'LBL_APP_DEPRECATED_DOWNLOAD', text: 'DESCARGAR' },
  { label: 'LBL_CONFIG_NOT_SELECTED', text: 'Ninguna configuración seleccionada' },
  { label: 'LBL_CONFIG_NOT_ACTIVE', text: 'Parece que la configuración seleccionada no está activa' },
  { label: 'LBL_CLEAR_APP_TITLE', text: 'LIMPIAR APLICACIÓN' },
  { label: 'LBL_CLEAR_APP_MESSAGE', text: '¿ESTÁS SEGURO QUE QUIERES LIMPIAR LA APLICACIÓN?' },
  { label: 'LBL_VPN_PERMISSION_DENIED', text: 'ERROR AL ESTABLECER CONEXIÓN VPN' },
  { label: 'LBL_VPN_PERMISSION_DENIED_TEXT', text: 'Disculpa, no se pudo establecer la conexión VPN. Verifica tus ajustes de VPN y que ninguna otra app esté usando la VPN.' },
  { label: 'LBL_VPN_PERMISSION_DENIED_BTN', text: 'ABRIR AJUSTES DE VPN' },
  { label: 'LBL_YES', text: 'Sí' },
  { label: 'LBL_NO', text: 'No' },
  { label: 'LBL_CONFIG_IMPORT_TITLE', text: 'IMPORTAR CONFIGURACIÓN' },
  { label: 'LBL_CONFIG_IMPORT_MESSAGE', text: 'SE ENCONTRÓ UNA CONFIGURACIÓN EN EL PORTAPAPELES. ¿DESEAS IMPORTARLA?' },
  { label: 'LBL_CONFIG_IMPORT_BTN_IMPORT', text: 'IMPORTAR' },
  { label: 'LBL_LIMITER_TITLE', text: 'LÍMITE ALCANZADO' },
  { label: 'LBL_LIMITER_TEXT', text: 'Lo sentimos, se alcanzó el número máximo de conexiones permitidas. Intenta más tarde o contacta con soporte.' },
  { label: 'LBL_VALIDATING_ACCESS', text: 'Validando tu acceso...' },
  { label: 'LBL_DNS_FORWARDING_DISABLED', text: '<b>Reenvío DNS deshabilitado</b>' },
  { label: 'LBL_DNS_FORWARDING_ENABLED', text: '<b>Reenvío DNS habilitado</b>' },
  { label: 'LBL_QUANTITY_PAYLOAD', text: '<b>PAYLOADS: %s</b>' },
  { label: 'LBL_QUANTITY_SNI', text: '<b>SNI: %s</b>' },
  { label: 'LBL_QUANTITY_PROXY', text: '<b>PROXIES: %s</b>' },
  { label: 'LBL_QUANTITY_SERVER', text: '<b>SERVIDORES: %s</b>' },
  { label: 'LBL_QUANTITY_PROCESS', text: '<b>PROCESOS: %s</b>' },
  { label: 'LBL_PING_STARTED', text: '<b>PING INICIADO</b>' },
  { label: 'LBL_PING_MESSAGE', text: '<i>Ping: %sms</i>' },
  { label: 'LBL_PING_STOPPED', text: '<b>PING PARADO</b>' },
  { label: 'LBL_ASSISTANT_TITLE', text: 'ACTIVAR ASISTENTE' },
  { label: 'LBL_ASSISTANT_TEXT', text: 'Para continuar, debes configurar la aplicación ({app_name}) como asistente' },
  { label: 'LBL_ASSISTANT_BUTTON', text: '<b>ABRIR CONFIGURACIONES</b>' },
  { label: 'LBL_FORCE_AIRPLANE_MODE_TOGGLE', text: '<b>Intentando activar y desactivar el modo avión...</b>' },
  { label: 'LBL_MENU_HOTSPOT_TITLE', text: 'ENCENDER/APAGAR HOTSPOT' },
  { label: 'LBL_MENU_HOTSPOT_DESCRIPTION', text: 'Al hacer clic, el hotspot del dispositivo se encenderá o apagará.' },
  { label: 'LBL_MENU_AIRPLANE_TITLE', text: 'ACTIVAR/DESACTIVAR MODO AVIÓN' },
  { label: 'LBL_MENU_AIRPLANE_DESCRIPTION', text: 'Al hacer clic, el modo avión se activará o desactivará.' },
  { label: 'LBL_MENU_APN_TITLE', text: 'ABRIR CONFIGURACIÓN DE APN' },
  { label: 'LBL_MENU_APN_DESCRIPTION', text: 'Al hacer clic, se abrirá la configuración APN del dispositivo.' },
  { label: 'LBL_MENU_NETWORK_TITLE', text: 'ABRIR CONFIGURACIÓN DE RED' },
  { label: 'LBL_MENU_NETWORK_DESCRIPTION', text: 'Al hacer clic, se abrirá la configuración de red del dispositivo.' },
  { label: 'LBL_MENU_BATTERY_TITLE', text: 'DESACTIVAR OPTIMIZACIÓN DE BATERÍA' },
  { label: 'LBL_MENU_BATTERY_DESCRIPTION', text: 'Al hacer clic, se desactivará la optimización de batería' },
  { label: 'LBL_MENU_CLEAN_APP_TITLE', text: 'LIMPIAR DATOS DE LA APP' },
  { label: 'LBL_MENU_CLEAN_APP_DESCRIPTION', text: 'Al hacer clic, todos los datos de la app se borrarán.' },
];

export default AppTextDefault;
